In [1]:
import gcinfo

gcinfo.list_resources(gcinfo.search_datasets(query='title:"Immigrants to Canada, by country of last permanent residence"')["results"][0])

=== Immigrants to Canada, by country of last permanent residence ===
ID: fc6ad2eb-51f8-467c-be01-c4bda5b6186b
Org: Statistics Canada | Statistique Canada
Notes: <p>This table contains 25 series, with data for years 1955 - 2013 (not all combinations necessarily have data for all years). This table contains data described by the following dimensions (Not all co...
  [CSV     ] Dataset
           https://www150.statcan.gc.ca/n1/tbl/csv/17100010-fra.zip
  [CSV     ] Dataset
           https://www150.statcan.gc.ca/n1/tbl/csv/17100010-eng.zip
  [XML     ] Dataset
           https://www150.statcan.gc.ca/n1/tbl/sdmx/17100010-SDMX.zip

In [2]:
df_origin, df_origin_meta = gcinfo.download_zip("https://www150.statcan.gc.ca/n1/tbl/csv/17100010-eng.zip")

Using cached file: cache\17100010-eng.zip

In [6]:
df_origin_2013 = df_origin[df_origin["REF_DATE"].apply(lambda x: x.split("-")[0]) == "2013"]
df_origin_2013.head()

,REF_DATE,GEO,DGUID,Last permanent residence,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
4828,2013-01,Canada,2011A000011124,Total immigrants,Persons,249,units,0,v16,1.1,58246,NaN,NaN,NaN,0
4829,2013-01,Canada,2011A000011124,Total Europe,Persons,249,units,0,v17,1.2,7648,NaN,NaN,NaN,0
4830,2013-01,Canada,2011A000011124,Great Britain,Persons,249,units,0,v18,1.3,1382,NaN,NaN,NaN,0
4831,2013-01,Canada,2011A000011124,France,Persons,249,units,0,v19,1.4,1779,NaN,NaN,NaN,0
4832,2013-01,Canada,2011A000011124,Germany,Persons,249,units,0,v20,1.5,251,NaN,NaN,NaN,0

In [7]:
df_origin_1955 = df_origin[df_origin["REF_DATE"].apply(lambda x: x.split("-")[0]) == "1955"]
df_origin_1955.head()

,REF_DATE,GEO,DGUID,Last permanent residence,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1955-01,Canada,2011A000011124,Total immigrants,Persons,249,units,0,v16,1.1,17627,NaN,NaN,NaN,0
1,1955-01,Canada,2011A000011124,Total Europe,Persons,249,units,0,v17,1.2,13775,NaN,NaN,NaN,0
2,1955-01,Canada,2011A000011124,Great Britain,Persons,249,units,0,v18,1.3,4270,NaN,NaN,NaN,0
3,1955-01,Canada,2011A000011124,France,Persons,249,units,0,v19,1.4,343,NaN,NaN,NaN,0
4,1955-01,Canada,2011A000011124,Germany,Persons,249,units,0,v20,1.5,1921,NaN,NaN,NaN,0